version: '3.9'

services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
#    ports:
#      - '2206:3306'
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    networks:
      - database

  node:
    image: 'node:18.0-alpine3.15'
    restart: unless-stopped
    volumes:
      - ../:/var/www/html
    working_dir: /var/www/html
    command: npm run start
    networks:
      - database

networks:
  database: