services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - '2206:3306'
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    networks:
      - database

  node:
    build:
        context: ../
        dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ../:/var/www/html
    networks:
      - database

networks:
  database: